### ISSUE TITLE
Navigation bar seems broken on mobile

### ISSUE THREAD

**Issue by tikkss** [red-data-tools/red-data-tools.github.io#15]
Looks like the `navigation bar` on mobile in [Red Data Tools website](https://red-data-tools.github.io/) seems broken.

The title of the navigation bar ("Red Data Tools") and the elements of the hamburger menu overlap. While the hamburger menu remains functional and can be tapped.

![image](https://github.com/red-data-tools/red-data-tools.github.io/assets/4122070/e05c01f7-2926-422c-994f-27c2f59d815a)

**Comment by kou** [comment]
Oh... We may need to update Bootstrap too...
https://github.com/red-data-tools/red-data-tools.github.io/blob/master/assets/stylesheets/_bootstrap.scss

**Comment by kou** [comment]
NOTE: Bootstrap isn't our requirement. We can switch to other OSS CSS framework if needed.
